name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.32'

    - name: Install dependencies
      run: |
        cpanm --installdeps .

    - name: Run tests
      run: |
        perl tests/login_test.pl